apiVersion: v1
kind: Pod
metadata:
  name: vkubelet-fdn-openwhisk-0
spec:
  containers:
  - name: jaeger-tracing
    image: jaegertracing/all-in-one:1.22
  - name: fdn-monitor
    image: ansjin/fdn-monitor
    imagePullPolicy: Always
    env:
    - name: CLUSTER_API_GW_ACCESS_TOKEN
      value: hello
    - name: CLUSTER_AUTH
      value: 
    - name: CLUSTER_GATEWAY_PORT
      value: "31001"  
    - name: CLUSTER_HOST
      value: 
    - name: CLUSTER_KUBERNETES_PROMETHEUS_PORT
      value: "30009"
    - name: CLUSTER_NAME
      value: edge_cluster 
    - name: CLUSTER_SERVERLESS_PLATFROM_PROMETHEUS_PORT
      value: "30010"
    - name: CLUSTER_TYPE
      value: OPENWHISK   
    - name: CLUSTER_USERNAME
      value: admin
    - name: DEFAULT_LOGGING_PERIOD
      value: "30"   

    - name: INFLUXDB_ADMIN_TOKEN
      value:    
    - name: INFLUXDB_BUCKET
      value: 
    - name: INFLUXDB_HOST
      value:  
    - name: INFLUXDB_ORG
      value: 
    - name: INFLUXDB_PORT
      value: "8086"   
    - name: INFLUXDB_TABLE_FUNCTIONS
      value: 
    - name: INFLUXDB_TABLE_INFRA
      value:    
  - name: vkubelet-fdn-openwhisk-0
    image: ansjin/virtual-kubelet:fdn5
    # "IfNotPresent" is used to prevent Minikube from trying to pull from the registry (and failing) in the first place.
    imagePullPolicy: Always
    args:
    - /virtual-kubelet
    - --nodename
    - vkubelet-fdn-openwhisk-0
    - --provider
    - fdn
    - --provider-config
    - /vkubelet-fdn-openwhisk-0-cfg.json
    - --startup-timeout
    - 10s
    - --serverless-platform-name
    - openwhisk
    - --serverless-platform-apihost
    - ""
    - --serverless-platform-auth
    - ""
    - --klog.v
    - "2"
    - --klog.logtostderr
    - --log-level
    - debug
    - --trace-exporter
    - jaeger
    - --trace-sample-rate=always
    env:
    - name: JAEGER_AGENT_ENDPOINT
      value: localhost:6831
    - name: KUBELET_PORT
      value: "10250"
    - name: VKUBELET_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  serviceAccountName: virtual-kubelet
